version: 1.0.{build}  
image: Visual Studio 2017

environment:  
  DOCKER_USER:
    secure: 1XrH+FwCALwaZSkP8gJK6w==
  DOCKER_PASS:
    secure: Lg7PbpxV+8GmoLAdkQGeoQ==
install:  
    - docker version
build_script:  
    - dotnet restore
    - docker build -t sosemivigelant .\src\SoSemiVigelant
deploy_script:  
    - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
    - docker push sosemivigelant