version: 1.0.{build}  
image: Visual Studio 2017

environment:  
  DOCKER_USER:
    secure: 1XrH+FwCALwaZSkP8gJK6w==
  DOCKER_PASS:
    secure: Lg7PbpxV+8GmoLAdkQGeoQ==
install:  
    - docker version
before_build:  
    - dotnet restore .\src\SoSemiVigelant
build_script:  
    - dotnet build .\src\SoSemiVigelant
    - dotnet publish .\src\SoSemiVigelant
    - npm run build .\src\SoSemiVigelant.FrontEnd
after_build:  
    - docker build -t dekker/sosemivigelant .\src\SoSemiVigelant
    - docker build -t dekker/sosemivigelantt.frontend .\src\SoSemiVigelant.FrontEnd
deploy_script:  
    #- docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
    - docker login -u="dekker" -p="67251425"
    - docker push dekker/sosemivigelant
    - docker push dekker/sosemivigelant.frontend