# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - dotnet restore src/SoSemiVigelant
          - dotnet build  src/SoSemiVigelant
#          - dotnet test TestName
          - dotnet publish src/SoSemiVigelant
#          - npm run build src/SoSemiVigelant.FrontEnd
          - docker build -t dekker/sosemivigelant.api /src/SoSemiVigelant
          - docker build -t dekker/sosemivigelant src/SoSemiVigelant.FrontEnd
          - docker login -u="dekker" -p="PipeIt!1"
          - docker push dekker/sosemivigelant.api
          - docker push dekker/sosemivigelant